<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.o8Ey2ki' shared service.

return $this->privates['.service_locator.o8Ey2ki'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'usuario' => ['privates', '.errored..service_locator.o8Ey2ki.App\\Entity\\Usuarios', NULL, 'Cannot autowire service ".service_locator.o8Ey2ki": it references class "App\\Entity\\Usuarios" but no such service exists.'],
], [
    'usuario' => 'App\\Entity\\Usuarios',
]);
