<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.e7XCCer' shared service.

return $this->privates['.service_locator.e7XCCer'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\UsuariosController::delete' => ['privates', '.service_locator.o8Ey2ki', 'get_ServiceLocator_O8Ey2kiService.php', true],
    'App\\Controller\\UsuariosController::edit' => ['privates', '.service_locator.o8Ey2ki', 'get_ServiceLocator_O8Ey2kiService.php', true],
    'App\\Controller\\UsuariosController::index' => ['privates', '.service_locator.eFwWtZx', 'get_ServiceLocator_EFwWtZxService.php', true],
    'App\\Controller\\UsuariosController::show' => ['privates', '.service_locator.o8Ey2ki', 'get_ServiceLocator_O8Ey2kiService.php', true],
    'App\\Controller\\UsuariosController:delete' => ['privates', '.service_locator.o8Ey2ki', 'get_ServiceLocator_O8Ey2kiService.php', true],
    'App\\Controller\\UsuariosController:edit' => ['privates', '.service_locator.o8Ey2ki', 'get_ServiceLocator_O8Ey2kiService.php', true],
    'App\\Controller\\UsuariosController:index' => ['privates', '.service_locator.eFwWtZx', 'get_ServiceLocator_EFwWtZxService.php', true],
    'App\\Controller\\UsuariosController:show' => ['privates', '.service_locator.o8Ey2ki', 'get_ServiceLocator_O8Ey2kiService.php', true],
], [
    'App\\Controller\\UsuariosController::delete' => '?',
    'App\\Controller\\UsuariosController::edit' => '?',
    'App\\Controller\\UsuariosController::index' => '?',
    'App\\Controller\\UsuariosController::show' => '?',
    'App\\Controller\\UsuariosController:delete' => '?',
    'App\\Controller\\UsuariosController:edit' => '?',
    'App\\Controller\\UsuariosController:index' => '?',
    'App\\Controller\\UsuariosController:show' => '?',
]);
